# Generated by Django 5.1.4 on 2025-01-07 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persondetailsmodel',
            old_name='last_modified',
            new_name='last_modifie',
        ),
    ]
